#可选 - (侧边的工作流名称)
name: 吾爱论坛签到定时任务
# 运行的工作流名称（在列表展示）
run-name: ${{ github.actor }} 吾爱论坛签到定时任务
#指定此工作流的触发器: 每次有人将更改推送到存储库或合并拉取请求时，都会触发工作流运行
on:
  #手动触发器
  workflow_dispatch:
  # schedule:    # 删除任务
  #   - cron: '59 23 * * *' # by https://crontab.guru/every-five-minutes
#将工作流中运行的所有作业组合在一起
jobs:
  #  定义该工作的名称
  pojie52_task:
    #    最新版本的 Ubuntu Linux 运行器上运行。这意味着作业将在 GitHub 托管的新虚拟机上执行
    runs-on: ubuntu-latest
    #    将作业中运行的所有步骤组合在一起。此部分下嵌套的每个项都是单独的操作或 shell 脚本
    steps:
      #     关键字指定此步骤将运行操作。这是一个将存储库签出到运行器上的操作，允许您针对代码运行脚本或其他操作（例如构建和测试工具）。每当工作流针对存储库的代码运行时，都应使用签出操作。
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.11.4'
          architecture: 'x64'
      
      #      关键字告诉作业在运行器上执行命令。在这种情况下，您正在使用安装软件测试包。
      - name: Upgrade pip
        run: pip install --upgrade pip
      #      - run: ifconfig
      #      #      运行一条shell命令试试

      - name: Install Dependencies
        run: pip install -r requirements.txt
      
      - name: Run Script
        run: python task.py
    #      - run: python PORD_Continuity/APS.py

    env:
      COOKIE_CONFIG: ${{ secrets.COOKIE_CONFIG }}
      SENDKEY: ${{ secrets.SENDKEY }}
      WX_TOKEN: ${{ secrets.WX_TOKEN }}
      UIDS: ${{  secrets.UIDS  }}
      SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
      SMTP_SSL: ${{ secrets.SMTP_SSL }}
      SMTP_EMAIL: ${{ secrets.SMTP_EMAIL }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      SMTP_NAME: ${{ secrets.SMTP_NAME }}